ALTER TABLE "tbl_ride"
RENAME COLUMN "price" TO "pricePerKm";

ALTER TABLE "tbl_booking"
ADD COLUMN "distanceKm" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "unitPricePerKm" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "tbl_booking"
ALTER COLUMN "distanceKm" DROP DEFAULT,
ALTER COLUMN "unitPricePerKm" DROP DEFAULT;

ALTER TABLE "tbl_waiting_list"
ADD COLUMN "pickupLat" DOUBLE PRECISION,
ADD COLUMN "pickupLon" DOUBLE PRECISION,
ADD COLUMN "dropoffLat" DOUBLE PRECISION,
ADD COLUMN "dropoffLon" DOUBLE PRECISION;
